name: Release üöÄ

on:
  release:
    types: [published]

jobs:
  build-docs:
    name: Build docs ‚öôÔ∏è
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      
      - name: Setup node 16
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          cd website/
          yarn
        
      - name: Build documentation
        run: |
          cd website/
          yarn build
      - name: Compress website build
        run: |
          cd website/
          tar czf build.tar.gz build/
      
      - name: Archive website build
        uses: actions/upload-artifact@v3
        with:
          name: docs-website
          path: website/build.tar.gz
          retention-days: 3

  preview:
    name: Release docs üöÄ
    runs-on: ubuntu-latest
    needs: [build-docs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      
      - name: Setup node 16
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: |
          cd website/
          yarn
      
      - name: Download website build
        uses: actions/download-artifact@v3
        with:
          name: docs-website
          path: website/

      - name: Extract website build
        run: |
          cd website
          tar -xf build.tar.gz
        
      - name: Deploy release
        run: |
          cd website/
          yarn run netlify deploy --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} --dir build/ --prod
